### ISSUE TITLE
.viewportrc errors

### ISSUE THREAD

**Issue by SteBurz** [K15t/gulp-viewport#13]
**Password**
Issue:
You can't use special characters in your confluence password, if you use this plugin. Reason is that the password doesn't get encoded. If you try to upload your Theme with gulp, you get an error 301 (permission error).

**Confluence - URL**
Issue:
If you have a confluence-base-url e.g. http://localhost:1990/ and insert this url in your .viewportrc you get a 404 Theme not found error, because of the last "/".

**Comment by skleinei** [comment]
These are two issues:

1. The issue with the password is really just limited some special characters, actually I only know about semicolons. The underlying issue is this one: https://github.com/npm/ini/issues/42. Reason: semicolons in INI files are handled as comments. Solution: encode semicolons in ini-file, like this:

        [DEV]
        confluenceBaseUrl=http://localhost:1990/confluence
        username=admin
        password=\;admin

https://github.com/K15t/viewport-tools will do this since 0.0.4.

2. The trailing slashes have been fixed in the last commit. Will be released with 2.3.0.
